-- Jira mirror (was raw/jira/tickets.sqlite). Read-only at query time; written
-- by scripts/jira_sync.py + scripts/classify_jira.py. Idempotent.
CREATE TABLE IF NOT EXISTS tickets (
  key                    TEXT PRIMARY KEY,
  project                TEXT NOT NULL,
  type                   TEXT,
  status                 TEXT,
  status_category        TEXT,
  priority               TEXT,
  resolution             TEXT,
  summary                TEXT,
  description_text       TEXT,
  description_raw_json   TEXT,
  resolution_text        TEXT,
  comment_count          INTEGER DEFAULT 0,
  comments_text          TEXT,
  comments_raw_json      TEXT,
  functional_area        TEXT,
  components_json        TEXT,
  labels_json            TEXT,
  reporter_account_id    TEXT,
  reporter_display_name  TEXT,
  assignee_account_id    TEXT,
  assignee_display_name  TEXT,
  parent_key             TEXT,
  epic_key               TEXT,
  links_json             TEXT,
  external_urls_json     TEXT,
  attachments_json       TEXT,
  created_at             TEXT NOT NULL,
  updated_at             TEXT NOT NULL,
  resolved_at            TEXT,
  fetched_at             TEXT NOT NULL,
  normalized_at          TEXT NOT NULL,
  source_filter          TEXT,
  triage_tier            TEXT,
  triage_reason          TEXT,
  last_triaged_at        TEXT,
  embedding_id           INTEGER
);
CREATE INDEX IF NOT EXISTS idx_functional_area ON tickets(functional_area);
CREATE INDEX IF NOT EXISTS idx_project_status  ON tickets(project, status_category);
CREATE INDEX IF NOT EXISTS idx_updated         ON tickets(updated_at);
CREATE INDEX IF NOT EXISTS idx_triage          ON tickets(triage_tier);
CREATE INDEX IF NOT EXISTS idx_resolved        ON tickets(resolved_at);

CREATE TABLE IF NOT EXISTS sync_runs (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  started_at       TEXT NOT NULL,
  ended_at         TEXT,
  filter_name      TEXT,
  mode             TEXT,
  tickets_fetched  INTEGER,
  tickets_new      INTEGER,
  tickets_updated  INTEGER,
  errors_json      TEXT,
  status           TEXT
);

CREATE TABLE IF NOT EXISTS custom_field_map (
  field_name   TEXT NOT NULL,
  project      TEXT NOT NULL,
  field_id     TEXT NOT NULL,
  cached_at    TEXT NOT NULL,
  PRIMARY KEY (field_name, project)
);

CREATE TABLE IF NOT EXISTS ticket_module_tags (
  ticket_key         TEXT NOT NULL,
  module_slug        TEXT NOT NULL,
  confidence         DOUBLE PRECISION NOT NULL,
  reason             TEXT,
  source             TEXT NOT NULL,
  classified_at      TEXT NOT NULL,
  classifier_version TEXT NOT NULL,
  PRIMARY KEY (ticket_key, module_slug),
  FOREIGN KEY (ticket_key) REFERENCES tickets(key)
);

CREATE TABLE IF NOT EXISTS ticket_classifications (
  ticket_key         TEXT PRIMARY KEY,
  type_bucket        TEXT NOT NULL,
  status_bucket      TEXT NOT NULL,
  is_bug             INTEGER NOT NULL,
  is_resolved        INTEGER NOT NULL,
  priority_bucket    TEXT,
  classified_at      TEXT NOT NULL,
  classifier_version TEXT NOT NULL,
  FOREIGN KEY (ticket_key) REFERENCES tickets(key)
);

CREATE INDEX IF NOT EXISTS idx_tags_module            ON ticket_module_tags(module_slug);
CREATE INDEX IF NOT EXISTS idx_tags_confidence        ON ticket_module_tags(confidence);
CREATE INDEX IF NOT EXISTS idx_tags_module_confidence ON ticket_module_tags(module_slug, confidence);
CREATE INDEX IF NOT EXISTS idx_class_type             ON ticket_classifications(type_bucket);
CREATE INDEX IF NOT EXISTS idx_class_status           ON ticket_classifications(status_bucket);
CREATE INDEX IF NOT EXISTS idx_class_priority         ON ticket_classifications(priority_bucket);
CREATE INDEX IF NOT EXISTS idx_class_is_bug           ON ticket_classifications(is_bug);
