-- PMS config catalog (was raw/configs/configs.sqlite). Read-only at query time;
-- built by scripts/build_config_db.py + enrich_config_db.py. Idempotent.
--
-- The SQLite FTS5 virtual table `configs_fts` + its 3 sync triggers are REPLACED
-- by a pg_trgm GIN index (fuzzy property-name match). The config_lookup fuzzy
-- path uses ILIKE + similarity() ordering against this index.
--
-- NOTE (prod): CREATE EXTENSION needs privilege. pg_trgm is on the AWS RDS
-- allowed-extensions list; if the wis_conwo role lacks CREATE EXTENSION, DevOps
-- must run `CREATE EXTENSION pg_trgm;` once before first deploy.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS configs (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_name          TEXT NOT NULL,
    service                TEXT NOT NULL,
    server                 TEXT NOT NULL CHECK (server IN ('com', 'in', 'both')),
    description            TEXT,
    data_type              TEXT,
    default_value          TEXT,
    customizable           INTEGER,
    criteria_priority_list TEXT,
    category               TEXT,
    UNIQUE (property_name, service, server)
);

CREATE TABLE IF NOT EXISTS jira_links (
    property_name TEXT NOT NULL,
    jira_key      TEXT NOT NULL,
    relevance     DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (property_name, jira_key)
);

CREATE TABLE IF NOT EXISTS module_links (
    property_name TEXT NOT NULL,
    module_slug   TEXT NOT NULL,
    link_type     TEXT NOT NULL,
    PRIMARY KEY (property_name, module_slug)
);

CREATE TABLE IF NOT EXISTS dependencies (
    property_a TEXT NOT NULL,
    property_b TEXT NOT NULL,
    dep_type   TEXT NOT NULL CHECK (dep_type IN ('functional','co_occurrence','structural')),
    direction  TEXT NOT NULL CHECK (direction IN ('a_requires_b','b_requires_a','bidirectional','correlated')),
    confidence DOUBLE PRECISION NOT NULL,
    evidence   TEXT,
    PRIMARY KEY (property_a, property_b, dep_type)
);

-- Replaces FTS5: trigram indexes power the config_lookup fuzzy fallback.
CREATE INDEX IF NOT EXISTS idx_configs_property_trgm
    ON configs USING gin (property_name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_configs_description_trgm
    ON configs USING gin (description gin_trgm_ops);
